# Site settings
title: Obsidian.css
email: charlespeters42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Obsidian.css is a modular CSS library that focuses on code common to most projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://obsidian.charlespeters.net"
# url: ""
source: _source

# Social
github: https://github.com/charlespeters/obsidian
npm: https://www.npmjs.com/package/obsidian.css
twitter: https://twitter.com/obsidiancss

# Package Info
version: v2.1.3
gzip_size: 7.7kb
selectors: 870
rules: 824


# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Build Settings
markdown: kramdown
permalink: pretty

exclude: ["README.md", "node_modules", "paths.js", "package.json", "gulpfile.babel.js", "_assets/"]
include: ["node_modules/obsidian.css"]
