# Site settings
title: Obsidian.css
email: charlespeters42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Obsidian.css is a modular CSS library that focuses on code common to most projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://obsidiancss.github.io" # the base hostname & protocol for your site
twitter_username: obsidiancss
github_username: obsidiancss
npm_package: obsidian.css
source: _source


# Package Info
version: v2.1.3
gzip_size: 7.7kb
selectors: 870
rules: 824


# Collections
collections:
  docs:
    output: true
    permalink: /:path/

# Build Settings
markdown: kramdown
permalink: pretty

exclude: ["README.md", "node_modules", "paths.js", "package.json", "gulpfile.babel.js", "_assets/"]
include: ["node_modules/obsidian.css"]
